### ISSUE TITLE
classMachines in Main Activity is null after AsyncTask returns

### ISSUE THREAD

**Issue by hughesjeff** [Purdue-ACM-SIGAPP/PurdueLaundry#1]
When we pick a room from the selector, the machines return properly. Just need to make the classMachines properly return from the AsyncTask.

**Comment by vieck** [comment]
͡° ͜ʖ ͡°

**Comment by hughesjeff** [comment]
¯\_(ツ)_/¯

**Comment by hughesjeff** [comment]
Fixing this should also make the ListView work. If the ListView doesn't work, then that's another issue, but I'll work on that later.

**Comment by hughesjeff** [comment]
Fixed in commit 02a4fbdca30bc10b6af10c1a7804b8ea087459bc
