### ISSUE TITLE
Modify Google Analytics exception calls

### ISSUE THREAD

**Issue by bienzaaron** [Purdue-ACM-SIGAPP/PurdueLaundry#109]
Right now, they're being sent like this:
`AnalyticsHelper.getDefaultTracker().send(
                                    new HitBuilders.ExceptionBuilder()
                                            .setDescription("Error")
                                            .set("HTTP Code", String.valueOf(httpCode))
                                            .set("Message", response.message())
                                            .setFatal(false)
                                            .build());`

Currently, the HTTP Code and Message aren't visible in the GA Dashboard.

When I originally wrote this, I didn't realize GA wouldn't record those custom dimensions when it's written that way. The information should all be within the description, or we should create a custom dimension (I think?).

**Comment by vidia** [comment]
I tweaked this a bit in #114 as well.
