### ISSUE TITLE
Add UI and App Tests

### ISSUE THREAD

**Issue by hughesjeff** [Purdue-ACM-SIGAPP/PurdueLaundry#132]
In progress with https://github.com/Purdue-ACM-SIGAPP/PurdueLaundry-android/pull/121

**Comment by hughesjeff** [comment]
Lol

**Comment by vieck** [comment]
We should write Android Instrumentation and Mockito Unit Tests to get our test coverage greater than 85% and have very few espresso tests to follow the [testing pyramid](https://developer.android.com/training/testing/fundamentals)
