### ISSUE TITLE
Information Activity

### ISSUE THREAD

**Issue by hughesjeff** [Purdue-ACM-SIGAPP/PurdueLaundry#18]
Create a general information activity when you click on a specific machine. It should allow you to see where it is (picture), information on the machine, and a couple buttons, one of which is remind when finished, and another is remind when XYZ time is remaining.

**Comment by bwencke** [comment]
Is this view still relevant given the re-design? I know it isn't included in my design.

**Comment by hughesjeff** [comment]
Irrelevant now.
