### ISSUE TITLE
Be notified when any washer or dryer opens up in a dorm

### ISSUE THREAD

**Issue by mhoc** [Purdue-ACM-SIGAPP/PurdueLaundry#22]
If all washers and dryers are taken, make a button visible which users can click to be notified when any one washer/dryer opens up.

**Comment by bwencke** [comment]
![notify when available](https://cloud.githubusercontent.com/assets/2365868/11289143/0d5ffc3c-8ef8-11e5-9335-7346d973f657.png)

Click on "Notify Me When A Washer Is Available" to see it in action: https://projects.invisionapp.com/share/BE43ZCS7N#/screens/100043833

**Comment by mhoc** [comment]
:+1: But we'd need two buttons; one for the washer and one for the dryer.

**Comment by bwencke** [comment]
Notification: 
![washer available](https://cloud.githubusercontent.com/assets/2365868/11289372/2b535d18-8efa-11e5-9bec-290264bb8e14.png)

**Comment by vidia** [comment]
This would be awesome! I think we should add it to the next release.

**Comment by mhoc** [comment]
Thanks!

**Comment by bienzaaron** [comment]
I'll take this one.

**Comment by vidia** [comment]
@bienzaaron What do you think about only showing the "Alert me when there is a XX available" only if there are currently no available machines? Rather than always being an option. It would make it a little cleaner for the User I think. What do you think?

**Comment by bienzaaron** [comment]
@vidia Yeah, sounds good to me. Doesn't make much sense to have it there when there's available washers, I think
