### ISSUE TITLE
Decrease size of tile which displays single washer summary

### ISSUE THREAD

**Issue by mhoc** [Purdue-ACM-SIGAPP/PurdueLaundry#23]
Right now that tile is very large such that only ~4 fit on the screen at any time. The same information could be divined to the user with a much smaller tile.

**Comment by mhoc** [comment]
![](https://cloud.githubusercontent.com/assets/2365868/11289143/0d5ffc3c-8ef8-11e5-9335-7346d973f657.png)

**Comment by bwencke** [comment]
![location view](https://cloud.githubusercontent.com/assets/2365868/11289310/809cd17e-8ef9-11e5-9424-8c09f2f9330e.png)

Interact at: https://projects.invisionapp.com/share/BE43ZCS7N#/screens/100043833

**Comment by hughesjeff** [comment]
Irrelevant now.
