### ISSUE TITLE
Support sending timer alerts when application has been closed. 

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM-SIGAPP/PurdueLaundry#41]
Right now, if the app is closed the timer notification is not updated and the alarm isn't triggered.

Either remove the notification on close (not ideal, but makes it obvious to the user)
or (more ideal) use alarmmanager http://androidideasblog.blogspot.co.uk/2011/07/alarmmanager-and-notificationmanager.html

**Comment by vidia** [comment]
Actually I think that storing the data in NotificationCreator in a NotificationService would manage this. Instead of it being stored in the static space. 

I THINK that just turning it into an instance that gets referred to in those places would fix this issue. Then the timers would only fail if the app is force closed from a task manager.

**Comment by vidia** [comment]
This is related to the following review on the Play store: 

Has some bugs An very useful app but unfortunately the bugs deter it from getting a 5 stars. The notifications after the machines are done do not go away and there's no way to get rid of them. The app also crashes when I try to forcefully rid the notification.

The crash is fixed on Master, but the problem still persists.

**Comment by hughesjeff** [comment]
This was fixed, but this never got closed.
