### ISSUE TITLE
Setting a home location.

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM-SIGAPP/PurdueLaundry#45]
Edit: Create a way to set a "favorite" or "home" location in the list. This way the user doesn't have to scroll all the way to their dorm every time. It also allows the user to quickly refer to the number of open machines in the room.

**Comment by hughesjeff** [comment]
This is fixed by opening to last viewed place

**Comment by vidia** [comment]
I don't think that is the best way to fix it honestly. Though the setting "home" isnt great either. 

A favorites view might be best I think. Especially because places like Windsor have multiple laundry rooms, don't they? 

I guess the question is if people look at multiple rooms regularly. I am sure we can figure that out from Google Analytics, but I am not sure how yet.

**Comment by vidia** [comment]
Right now we have a 50% bounce rate new users from the Location list and a 30% bounce overall. I am not entirely sure what is causing that, but I think if we add a home location and that rate changes at all this will help. 

Related to that we should have stats on how much a user has to scroll.

**Comment by jpitlor** [comment]
so...you think we should do a favorites view @vidia? are there enough people that bounce between a specific set of >1 rooms that it would be better than keeping it the way it is?
