### ISSUE TITLE
Add a debug location in the Location list on debug versions

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM-SIGAPP/PurdueLaundry#60]
Check for debug and add a location that has a machine of every type and status. 

With various times left for timers as well. 

(Or actually implement dagger and a debug version of the API client...)

**Comment by hughesjeff** [comment]
We are not doing DI. I'm putting my foot down on that one. (at least for the time being)

**Comment by vidia** [comment]
DI for certain segments wouldnt be a bad idea. As long as it is contained and there is a good wrapper around it. 

But I agree that it probably is overkill for the time being.

**Comment by jpitlor** [comment]
i think this is a good idea, especially because there are literally routes on the server that generate these example locations
