### ISSUE TITLE
Text formatting issues on Oneplus X

### ISSUE THREAD

**Issue by davidsun0** [Purdue-ACM-SIGAPP/PurdueLaundry#64]
On my Oneplus X (1080 x 1920px), the text formatting becomes squished on halls with long names.
For all hall listings, "Dryers Available" is wrapped into 2 lines, which moves the number of dryers and number of washers out of alignment.
<details><summary>

Screenshot</summary>

![screenshot_20161026-000937](https://cloud.githubusercontent.com/assets/7274320/19713032/ae187dd2-9b10-11e6-8f2b-121ae0f9262b.png)
</details>

**Comment by hughesjeff** [comment]
This is a known issue. We didn't have time to fix it in the release this week, but we have a couple other things we want to fix, and those, along with this fix, should be coming out in a couple weeks.

**Comment by vidia** [comment]
#53, we need to do this on a bunch of devices to make sure. Probably some font size changes will fix it easiest. That or truncation with "..."
