### ISSUE TITLE
When you first enter a machine view show a tutorial

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM-SIGAPP/PurdueLaundry#65]
Show as a snackbar that you can click in use machines.

**Comment by vieck** [comment]
@vidia There are also some libraries that can darken the entire screen and give a literal tutorial on how to use the app. I can look into some of those on android arsenal.

**Comment by vidia** [comment]
I have seen some of those. I am not ENTIRELY opposed to something like that, but I think they can be a little too in your face sometimes. 

I'd like to so somerhing more subtle I think so that users arent disrupted too much. 

UNLESS! Maybe this is a chance to A/B test :) That could be fun!

**Comment by vidia** [comment]
This should be fixed/avoided with #112 . It isnt a tutorial really, but it should help discoverability. 

We might want to throw a snackbar at least anyway to alert the user.

**Comment by vidia** [comment]
Handled by a snackbar on the first view.
