### ISSUE TITLE
Shreve West Dryer #4 is missing but exists IRL

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM-SIGAPP/PurdueLaundry#68]
Its not on the datasource so idk what we can do about it. But it may be worth adding some sort of reporting for this case.

**Comment by hughesjeff** [comment]
Also, Third Street is ALL OVER THE PLACE. http://wpvitassuds01.itap.purdue.edu/washalertweb/washalertweb.aspx?location=96ed9941-352d-478f-88c3-1a0320066464
I don't think this is something is necessary to handle if ITaP doesn't handle it, especially in the case that this would probably have to be hardcoded in some places, and I don't like that. 
We could check for 1 -> 2 -> 3, etc, but that would be dirty in my opinion. (see Third Street)

**Comment by vidia** [comment]
I think we should consider having a "ghost" machine when we KNOW there is a machine that isnt tracked. IE, inserting an "offline" machine into the list. 

Now it would be hard to KNOW when there is a missing machine. So maybe that would be a bad idea.

**Comment by hughesjeff** [comment]
I can't think of a good way to do this without some level of hardcoding, which would be *very* dirty.

**Comment by jpitlor** [comment]
i personally agree with jeff on this one, and if itap doesn't handle it, I don't think we should be expected to pick up the slack.

do we close it or do it?
