### ISSUE TITLE
Sometimes Timers Re-appear After Being Cancelled

### ISSUE THREAD

**Issue by hughesjeff** [Purdue-ACM-SIGAPP/PurdueLaundry#79]
I'll take this, as I believe I know what's causing it.

**Comment by vidia** [comment]
Let me know if its the race condition I guessed about. I am really curious about this one.

**Comment by vidia** [comment]
Did we fix this one? Was it part of the other notification issues?

**Comment by hughesjeff** [comment]
Crap, I wanted to talk to you about this. I'll discuss on Tuesday. We had... other issues we were working on.

**Comment by vidia** [comment]
@hughesjeff Whats the status on this?

**Comment by hughesjeff** [comment]
Fixed by #111
