### ISSUE TITLE
Add a way for a user to request a notification when a machine becomes available

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM-SIGAPP/PurdueLaundry#88]
And make it work offline probably.

**Comment by hughesjeff** [comment]
What's the difference between this and what we currently have? Is this for a specific machine, or just one in general when a machine in a room becomes available?

**Comment by vidia** [comment]
What we have is for when your load is finished. It would be nice to have a way to tell when ANY machine in a room becomes available. .

Obviously the user could simply set a timer on the machine that is nearly done, but I think it would be cleaner to have a contextual button or something that says "Tell me when a machine opens up" when all of the machines have shit in them. 

Then we can also take into accound "End of cycle" statuses. For example, with this feature a machine isnt available until it is actually "Available" (ie, the previous load has been removed).

**Comment by hughesjeff** [comment]
We have that...

**Comment by hughesjeff** [comment]
https://github.com/Purdue-ACM-SIGAPP/PurdueLaundry/pull/75

**Comment by vidia** [comment]
Cool. I need to run that at some point and see how it was implemented. 

Though I don't think that waits for the laundry to be removed? Does it?

**Comment by hughesjeff** [comment]
Not at all. It's a very primitive feature

**Comment by vidia** [comment]
Added in a previous version.
