### ISSUE TITLE
Make the app check that the API version matches what specific version the app requires

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM-SIGAPP/PurdueLaundry#91]
Because the server will periodically be updated with new features we will end up with a bunch of previous versions of API endpoints. Over time they will need to be deleted. 

When starting, the app should check with the server somehow to ensure that the compatible version of the API is available. If it is not available then the app should request that the user install an update.

**Comment by jpitlor** [comment]
I think this is solved with versioning. We can delete versions of the server as we see the endpoints stop getting hit
